#pragma once

#include <glad/glad.h>
#include <stack>

#include "Matrix.hpp"
#include "Shader.hpp"


enum class eModelType
{
    cube,
    sphere,
    cylinder
};

class Model
{
public:
    Model(const vec3& position, const vec3& orientation, const vec3& scale, const vec3& joint, std::string name);
    ~Model(void);

    void update(const mat4& parentTransform, Shader* shader);
    void render(Shader* shader);

    mat4 popMatrix(void);
    void pushMatrix(void) { stack.push(stack.top()); }
    void pushMatrix(const mat4& mat) { stack.push(mat); }

    // GETTERS
    const vec3& get_position(void) const { return (position); }
    const vec3& get_joint(void) const { return (joint); }
    const vec3& get_scaling(void) const { return (scaling); }
    
    // SETTERS
    void set_transform(const mat4& transform) { transform_ = transform; }
    void set_position(const vec3& t) { position = t; }
    void set_joint(const vec3& j) { joint = j; }
    void set_scaling(const vec3& s) { scaling = s; }


private:
    int number_of_indices; // the number of triangles of the model
    GLuint vao; // Vertex Array Object
    GLuint vbo; // Vertex Buffer Object
    GLuint ebo; // Element Buffer Object (or indices buffer object, ibo)

    std::stack<mat4> stack; // the stack matrix
    mat4 transform_; // the tranform generated by the Animator's keyFrames

    vec3 position; // the position (parent local-space)
    vec3 orientation; // the orientation (parent local-space)
    vec3 scale; // the scale
    vec3 world_position; // the position (world-space)

    vec3 joint; // the joint around which the bone rotates (local-space)
    vec3 scaling; // the value changed in animation as a modifier

    bool selected; // true if the model is selected

    std::string name;

    GLuint texture;
    GLuint texture_sm;
    GLuint texture_nl;

    void init_buffer_objects(int mode = GL_STATIC_DRAW);
    unsigned load_texture(char const* path);
};
